name: Simple Greeting API

on:
  repository_dispatch:
    types: [say_hello]

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: |
          echo "성공적으로 API 요청을 받았습니다!"
          echo "메시지: ${{ github.event.client_payload.message }}"
